package ch.hslu.sweng.group3;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class EditRoomFormFrame extends JFrame {
    private JLabel lblRoomID;
    private JTextField txtRoomID;
    private JLabel lblNumberOfSeats;
    private JTextField txtInputNumberOfSeats;
    private JButton btnExitForm;
    private JButton btnSaveRoom;
    private JPanel editRoomPanel;

    public EditRoomFormFrame(int roomID) {
        setTitle("Room Changes Form");
        setSize(800, 500);
        setLocationRelativeTo(null);
        setContentPane(editRoomPanel);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);

        Room r = App.roomDAO.getRoom(roomID);
        txtRoomID.setText(String.valueOf(r.getRoomID()));
        txtInputNumberOfSeats.setText(String.valueOf(r.getSeatsOfRoom()));

        //executes a sql update for a room, closes the form and goes to the previous frame afterwards
        btnSaveRoom.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Room changedRoom = App.roomDAO.getRoom(Integer.parseInt(txtRoomID.getText()));
                if (ExceptionCheck.isValuePositiveNumber(txtInputNumberOfSeats.getText()) == true) {
                    changedRoom.setSeatsOfRoom(Integer.parseInt(txtInputNumberOfSeats.getText()));
                    App.roomDAO.editRoom(changedRoom);
                }
                dispose();
                RoomAdministrationFrame roomAdministrationFrame = new RoomAdministrationFrame();
            }
        });

        // closes the form and goes to the previous frame
        btnExitForm.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                RoomAdministrationFrame roomAdministrationFrame = new RoomAdministrationFrame();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        editRoomPanel = new JPanel();
        editRoomPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        lblRoomID = new JLabel();
        lblRoomID.setText("Room Number");
        editRoomPanel.add(lblRoomID, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtRoomID = new JTextField();
        txtRoomID.setEditable(false);
        editRoomPanel.add(txtRoomID, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lblNumberOfSeats = new JLabel();
        lblNumberOfSeats.setText("Number of Seats");
        editRoomPanel.add(lblNumberOfSeats, new GridConstraints(2, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtInputNumberOfSeats = new JTextField();
        editRoomPanel.add(txtInputNumberOfSeats, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        btnSaveRoom = new JButton();
        btnSaveRoom.setText("Save");
        editRoomPanel.add(btnSaveRoom, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 40), null, 0, false));
        btnExitForm = new JButton();
        btnExitForm.setText("Cancel");
        editRoomPanel.add(btnExitForm, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 40), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return editRoomPanel;
    }

}




